name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Uncommented this line

      - name: Run tests
        run: pytest      
        
      - name: Auto-merge main into PR (auto-resolve conflicts)
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge origin/main -X theirs --no-edit --allow-unrelated-histories
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
