name: Sanitize Emojis

on:
  push:
    paths:
      - '**/*'
  pull_request:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install emoji

      - name: Remove emojis from all files
        run: python .github/scripts/remove_emojis.py

      - name: Commit and push changes if emojis were removed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: auto-remove emojis from content [bot]"
            git push
          fi
